name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
        "sudo rm -rf /opt/arryn-backend && \
         sudo mkdir -p /opt/arryn-backend && \
         sudo chown ec2-user:ec2-user /opt/arryn-backend && \
         cd /opt/arryn-backend && \
         git clone https://github.com/ARRYN-PI2/pi2-backend.git . && \
         git checkout main"
         
    - name: Setup environment from .env.prod
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
        "cd /opt/arryn-backend && \
         cp .env.prod .env && \
         echo 'MONGODB_URL=${{ secrets.MONGODB_URL }}' >> .env && \
         echo 'SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}' >> .env && \
         echo 'DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}' >> .env"
         
    - name: Create docker-compose.yml
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
        "cd /opt/arryn-backend && \
         cat > docker-compose.yml << 'EOF'
        version: '3.8'
        services:
          backend:
            build: .
            ports:
              - '8000:8000'
            env_file:
              - .env
            restart: unless-stopped
        EOF"
        
    - name: Deploy with Docker
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
        "cd /opt/arryn-backend && \
         docker-compose down || true && \
         docker-compose up -d --build"
         
    - name: Health Check
      run: |
        sleep 25
        curl -f http://${{ secrets.EC2_HOST }}:8000/ || echo "Health check failed, but deployment completed"